github.com:
    users:
        jonasvbiegel:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jonasvbiegel
