[general]
live_config_reload = true
import = ["./dracula.toml"]

[window]
padding = { x = 10, y = 10 }
opacity = 0.85
blur = true

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" } 
size = 10
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }

[mouse]
hide_when_typing = true
